In [1]:
# import pandas alias pd
import pandas as pd

### Reading Data Files into Pandas
Reference: (http://nbviewer.jupyter.org/github/justmarkham/pandas-videos/blob/master/pandas.ipynb)

In [2]:
# tab-seperated data into pandas data frame. the data is Chipotle orders
orders = pd.read_table('http://bit.ly/chiporders')

In [3]:
orders.head()  # head is a method of the data frame orders

order_id  ...  item_price
0         1  ...      $2.39 
1         1  ...      $3.39 
2         1  ...      $3.39 
3         1  ...      $2.39 
4         2  ...     $16.98 

[5 rows x 5 columns]

In [4]:
## Help on read_table method
pd.read_table?

In [21]:
# Let us read data on movie users. It is seperated by a pipe |
users = pd.read_table('http://bit.ly/movieusers')

In [22]:
users.head()

1|24|M|technician|85711
0       2|53|F|other|94043
1      3|23|M|writer|32067
2  4|24|M|technician|43537
3       5|33|F|other|15213
4   6|42|M|executive|98101

In [23]:
# The first row is read as column names
users = pd.read_table('http://bit.ly/movieusers', sep='|')
users.head()

1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

In [24]:
users = pd.read_table('http://bit.ly/movieusers', sep='|', header=None)
users.head()

0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213

In [25]:
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table('http://bit.ly/movieusers', sep='|', header=None, names=user_cols)
users.head()

user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [26]:
users['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...      
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

In [27]:
users.occupation

0         technician
1              other
2             writer
3         technician
4              other
           ...      
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

In [28]:
users.shape # attributes have no parenthesis

(943, 5)

In [29]:
users.dtypes

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [30]:
users.describe()

user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [31]:
users.describe(include='all')

user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

In [32]:
# UFO reports data seperated by comma
ufo = pd.read_table('http://bit.ly/uforeports', sep=',')

# read_csv has default comma as seperator
ufo = pd.read_csv('http://bit.ly/uforeports')

In [33]:
# ufo.Location = ufo.City + ', ' + ufo.State will not work

# You have to use bracket notation to define the Series name)
ufo['Location'] = ufo.City + ', ' + ufo.State
ufo.shape

(18241, 6)

In [34]:
ufo["Shape Reported"].unique()

array(['TRIANGLE', 'OTHER', 'OVAL', 'DISK', 'LIGHT', 'CIRCLE', 'CIGAR',
       'CYLINDER', 'FIREBALL', 'SPHERE', nan, 'RECTANGLE', 'FORMATION',
       'FLASH', 'CHEVRON', 'EGG', 'CONE', 'DIAMOND', 'VARIOUS',
       'TEARDROP', 'CROSS', 'DELTA', 'ROUND', 'DOME', 'PYRAMID',
       'CRESCENT', 'FLARE', 'HEXAGON'], dtype=object)

In [35]:
ufo["Shape Reported"].value_counts()

LIGHT        2803
DISK         2122
TRIANGLE     1889
OTHER        1402
CIRCLE       1365
SPHERE       1054
FIREBALL     1039
OVAL          845
CIGAR         617
FORMATION     434
VARIOUS       333
RECTANGLE     303
CYLINDER      294
CHEVRON       248
DIAMOND       234
EGG           197
FLASH         188
TEARDROP      119
CONE           60
CROSS          36
DELTA           7
CRESCENT        2
ROUND           2
FLARE           1
PYRAMID         1
DOME            1
HEXAGON         1
Name: Shape Reported, dtype: int64

### Missing Values

In [36]:
# Python has None object:   # null
import numpy as np
R1 = np.array([4, None, 5])
R1 # An array has only one data type. Here dtype=object is the common type

array([4, None, 5], dtype=object)

In [37]:
#  NaN ( Not a Number) is a special floating-point value by the standard IEEE 
R2 = np.array([4, np.nan, 5])
print(R2)
R2.dtype

[ 4. nan  5.]


dtype('float64')

In [38]:
print(5 + np.nan)
print(5*np.nan)
print(R2.sum())
np.nansum(R2)  # ignore NaN

nan
nan
nan


9.0

In [39]:
# Pandas
s7 = pd.Series([5, np.nan, 7, None]) #  upcast to a floating-point type to consider the NA
s7

0    5.0
1    NaN
2    7.0
3    NaN
dtype: float64

In [40]:
s7.isnull() 

0    False
1     True
2    False
3     True
dtype: bool

In [41]:
s7[s7.notnull()]

0    5.0
2    7.0
dtype: float64

In [42]:
# dropping NAs
s7.dropna()

0    5.0
2    7.0
dtype: float64

In [43]:
# NAs in data frames
df2 = pd.DataFrame([[5, 7, 2],
                   [9,  np.nan,  1],
                   [3,      8, np.nan]])
df2

0    1    2
0  5  7.0  2.0
1  9  NaN  1.0
2  3  8.0  NaN

In [44]:
# You can drop rows or columns, not single values
df2.dropna() # default is row-wise

0    1    2
0  5  7.0  2.0

In [45]:
df2.dropna(axis =1) #column-wise. 
#Also, how = 'any' is default. how = 'all' drops when all elements of a column are null

0
0  5
1  9
2  3

In [46]:
# Filling NAs
df2.fillna(0)

0    1    2
0  5  7.0  2.0
1  9  0.0  1.0
2  3  8.0  0.0

In [47]:
print(df2.fillna(method='ffill')) # forward 
print(df2.fillna(method='bfill', axis =1)) #backward
df2

   0    1    2
0  5  7.0  2.0
1  9  7.0  1.0
2  3  8.0  1.0
     0    1    2
0  5.0  7.0  2.0
1  9.0  1.0  1.0
2  3.0  8.0  NaN


0    1    2
0  5  7.0  2.0
1  9  NaN  1.0
2  3  8.0  NaN

### Aggregation

In [48]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})

In [49]:
df

A      B         C         D
0  foo    one  1.139433  0.522106
1  bar    one  0.492168  1.275858
2  foo    two -0.125089 -1.283297
3  bar  three  0.141662  1.044040
4  foo    two  0.712528  1.576451
5  bar    two  0.119389  0.878904
6  foo    one -1.138319  1.205415
7  foo  three  1.449812 -0.643328

In [50]:
grouped = df.groupby('A')

grouped

In [51]:
grouped.sum() # df.groupby('A').sum()

C         D
A                      
bar  0.753220  3.198802
foo  2.038365  1.377347

In [52]:
df.groupby('A').get_group('foo')

A      B         C         D
0  foo    one  1.139433  0.522106
2  foo    two -0.125089 -1.283297
4  foo    two  0.712528  1.576451
6  foo    one -1.138319  1.205415
7  foo  three  1.449812 -0.643328

In [53]:
grouped.agg(np.sum)

C         D
A                      
bar  0.753220  3.198802
foo  2.038365  1.377347

In [54]:
grouped.size()

A
bar    3
foo    5
dtype: int64

In [55]:
grouped.describe() #pandas.DataFrame.describe?

C                                ...         D                              
    count      mean       std       min  ...       25%       50%       75%       max
A                                        ...                                        
bar   3.0  0.251073  0.209091  0.119389  ...  0.961472  1.044040  1.159949  1.275858
foo   5.0  0.407673  1.047424 -1.138319  ... -0.643328  0.522106  1.205415  1.576451

[2 rows x 16 columns]

In [56]:
# Multiple functions
grouped['C'].agg([np.sum, np.mean, np.std])

sum      mean       std
A                                
bar  0.753220  0.251073  0.209091
foo  2.038365  0.407673  1.047424

In [57]:
df.groupby('A').aggregate('C').mean()

A
bar    0.251073
foo    0.407673
Name: C, dtype: float64

In [58]:
df.groupby('A').C.mean()

A
bar    0.251073
foo    0.407673
Name: C, dtype: float64

In [59]:
df.groupby('A')['C'].mean()

A
bar    0.251073
foo    0.407673
Name: C, dtype: float64

### Categorical Variables:
There are several ways to convert categorical variables: LabelEncoder, onehotencoder, and get_dummies

In [60]:
# Let us recall df
df

A      B         C         D
0  foo    one  1.139433  0.522106
1  bar    one  0.492168  1.275858
2  foo    two -0.125089 -1.283297
3  bar  three  0.141662  1.044040
4  foo    two  0.712528  1.576451
5  bar    two  0.119389  0.878904
6  foo    one -1.138319  1.205415
7  foo  three  1.449812 -0.643328

In [61]:
df_1 = pd.get_dummies(df)
df_1.head()

C         D  A_bar  A_foo  B_one  B_three  B_two
0  1.139433  0.522106      0      1      1        0      0
1  0.492168  1.275858      1      0      1        0      0
2 -0.125089 -1.283297      0      1      0        0      1
3  0.141662  1.044040      1      0      0        1      0
4  0.712528  1.576451      0      1      0        0      1

In [62]:
from sklearn.preprocessing import StandardScaler
list_1 = [[1000, 10], [999, 9], [1001, 11]]
scaler = StandardScaler()
scaler.fit(list_1)
scaler.transform(list_1)

array([[ 0.        ,  0.        ],
       [-1.22474487, -1.22474487],
       [ 1.22474487,  1.22474487]])

In [68]:
df_2 = scaler.fit_transform(df_1[['C','D']])
df_2

array([[ 1.05143447, -0.05281732],
       [ 0.19049937,  0.74480325],
       [-0.63052383, -1.96329644],
       [-0.27571411,  0.49949297],
       [ 0.48360331,  1.06289127],
       [-0.30533922,  0.32474651],
       [-1.97823467,  0.67026086],
       [ 1.46427468, -1.28608109]])

In [64]:
list_2 = [[1000, 10], [1000, 9], [1000, 11]]
scaler = StandardScaler()
scaler.fit(list_2)
scaler.transform(list_2)

array([[ 0.        ,  0.        ],
       [ 0.        , -1.22474487],
       [ 0.        ,  1.22474487]])

In [72]:
#Scale back the data to the original representation
scaler.inverse_transform(df_2). ## same as column C and D of df_1

array([[ 1.13943255,  0.5221063 ],
       [ 0.49216847,  1.27585806],
       [-0.12508924, -1.28329722],
       [ 0.14166209,  1.04403974],
       [ 0.71252846,  1.57645136],
       [ 0.11938949,  0.87890427],
       [-1.13831872,  1.20541547],
       [ 1.44981209, -0.64332845]])