In [1]:
import numpy as np

In [3]:
#Q1
# Use Numpy to create a 5x5 identity matrix
ident = np.eye(5)

ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
#Q2
#Write a function that accepts an array and return its revers (e.g., [1 2 3 4] -> [4 3 2 1])

# def reverse(arr):
#     return np.flip(arr)

def reverse(x):
  return(x[::-1])
        
a = np.random.randint(0, 10, 5)

print(a)

b = reverse(a)

print (b)

[4 7 9 7 3]
[3 7 9 7 4]


In [9]:
#Q3
# Write a code that replaces the negative values of an array with zero

arr = [1,2,-3,4]

for i in range(0,len(arr)):
    if arr[i] < 0:
        arr[i] = 0

print(arr)

[1, 2, 0, 4]


In [12]:
#Q4
# Create an array of shape 3x4 and swap column 1 and column 3

a2 = np.random.randint(10, size=(3, 4))

print(a2)

col1 = a2[:,0].copy()
col3 = a2[:,2].copy()
a2[:,0] = col3
a2[:,2] = col1

print(a2)

[[9 2 0 9]
 [2 3 6 4]
 [2 6 5 4]]
[[0 2 9 9]
 [6 3 2 4]
 [5 6 2 4]]


In [13]:
#Q5
# Create an array of shape 3x4 by drawing random numbers from a normal (Gaussian) distribution
# with mean 100 and standard deviation 15

np.random.normal(100, 15, (3, 4))

array([[ 94.83570187,  96.49073245, 101.34806213, 103.01072498],
       [ 95.73701455,  74.02818067,  92.50203326,  98.84166969],
       [130.29872822, 115.40402426, 109.92747674, 113.85857256]])